// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS-_bviHb49wlY-VinucCLsEusdHas9qQ',
    appId: '1:712969901589:web:8f42d57426fa5679eb201c',
    messagingSenderId: '712969901589',
    projectId: 'socialmediatest-a0d4e',
    authDomain: 'socialmediatest-a0d4e.firebaseapp.com',
    storageBucket: 'socialmediatest-a0d4e.firebasestorage.app',
    measurementId: 'G-7R34ZVPS9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB47XfNPGe9yUVAsnrYztY5nl4mDT8dEXc',
    appId: '1:712969901589:android:379ab90acaa7b142eb201c',
    messagingSenderId: '712969901589',
    projectId: 'socialmediatest-a0d4e',
    storageBucket: 'socialmediatest-a0d4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '#######',
    appId: '1:712969901589:ios:d43b627505ca8504eb201c',
    messagingSenderId: '712969901589',
    projectId: 'socialmediatest-a0d4e',
    storageBucket: 'socialmediatest-a0d4e.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia2',
  );
}
